# =============================================================================
# manual_scorer_parser.py — Extract "blind" samples for manual validation
# =============================================================================
#
# Purpose:
#   Extract all interactions from a Promptfoo eval.json (any strategy S1/S2/S3)
#   WITHOUT fields generated by the deterministic evaluator (score, pass,
#   gradingResult, assert, error, etc.). This allows a human rater to label
#   each interaction without bias, enabling later agreement analysis between
#   the deterministic scorer and human labels (addressing Reviewer Comment 2).
#
# Design:
#   - Generic: Works with any eval.json following the standard Promptfoo
#     schema (head/body/outputs), regardless of attack strategy or model.
#   - Blind: Deliberately excludes "ground truth" fields (marcador_exito, etc.)
#     that would telegraph the expected outcome to the human rater.
#   - Preserves: All context necessary for judgment (system prompt, user
#     prompt containing the attack, model output, latency).
#
# Usage:
#   python manual_scorer_parser.py <eval.json> <strategy_label> [output.json] [--exclude-vars k1,k2]
#
# Examples:
#   python manual_scorer_parser.py eval-S3-locals.json S3 blind_S3.json
#   python manual_scorer_parser.py eval-S1-locals.json S1_locals blind_S1_locals.json --exclude-vars marcador_exito
#
# =============================================================================

import json
import sys
import argparse


# Heuristic set of variable names that encode "ground truth" or expected
# outcomes used by the deterministic scorer. These must be excluded from the
# blind samples to prevent human rater bias. Can be extended per-invocation
# via --exclude-vars flag.
DEFAULT_EXCLUDE_VAR_KEYS = {
    "marcador_exito",      # S3: internal flag indicating successful injection
    "secret_value",        # S2 (if present): expected secret value
    "valor_secreto",       # Spanish variant
    "expected_output",     # Generic ground truth
    "ground_truth",        # Generic ground truth
}


def extract_prompt_parts(prompt_field):
    """
    Normalize the 'prompt' field from a Promptfoo output record.
    
    Promptfoo serializes prompts in various formats:
    - As a JSON string (most common): [{"role": "system", ...}, {"role": "user", ...}]
    - As a dict with "raw" key: {"raw": "..."}
    - As a plain string: "..."
    
    This function handles all three and returns (system_prompt, user_prompt).
    System and user prompts are extracted separately for clarity when reviewing.
    
    Args:
        prompt_field: The 'prompt' field from a Promptfoo output record.
    
    Returns:
        tuple: (system_prompt: str or None, user_prompt: str or None)
    """
    system_prompt, user_prompt = None, None

    # Attempt to parse prompt_field as JSON string if it's a string literal.
    # This is the most common case in Promptfoo eval.json files.
    if isinstance(prompt_field, str):
        try:
            parsed = json.loads(prompt_field)
            prompt_field = parsed
        except (json.JSONDecodeError, TypeError):
            # If parsing fails, treat as a plain string and fall through.
            pass

    # Case 1: prompt_field is a list of role/content messages (OpenAI format).
    if isinstance(prompt_field, list):
        user_parts = []
        for msg in prompt_field:
            if not isinstance(msg, dict):
                continue
            role = msg.get("role")
            content = msg.get("content")
            
            if role == "system":
                system_prompt = content
            elif role == "user":
                # Collect all user messages; join with newlines if multiple.
                if isinstance(content, str):
                    user_parts.append(content)
                else:
                    # If content is structured (dict/list), serialize to JSON.
                    user_parts.append(json.dumps(content, ensure_ascii=False))
        
        if user_parts:
            user_prompt = "\n".join(user_parts)
    
    # Case 2: prompt_field is a dict with "raw" or similar key.
    elif isinstance(prompt_field, dict):
        system_prompt = prompt_field.get("raw")
    
    # Case 3: prompt_field is already a plain string.
    elif isinstance(prompt_field, str):
        system_prompt = prompt_field

    return system_prompt, user_prompt


def extract_model_output_text(out):
    """
    Extract the model's raw output text from a Promptfoo output record.
    
    Priority order:
    1. 'text' field (raw model response, as returned by the model)
    2. 'response' field -> 'output' sub-field (if response is a dict)
    3. 'response' field as-is (fallback)
    
    The output is left unchanged (even if it encodes a tool call as JSON)
    so that the human rater sees exactly what the deterministic scorer
    evaluated, avoiding artifacts from reformatting.
    
    Args:
        out: A single output record from Promptfoo (model × hardening).
    
    Returns:
        str or None: The model's raw output text.
    """
    if out.get("text") is not None:
        return out["text"]
    
    resp = out.get("response")
    if isinstance(resp, dict):
        return resp.get("output", resp)
    
    return resp


def extract_samples(data, strategy_label, exclude_var_keys):
    """
    Extract all blind samples from a Promptfoo eval.json structure.
    
    Iterates through all test cases (rows) and all model outputs, building
    a sample record for each interaction. Filters out "ground truth" variables
    to maintain blindness, and explicitly excludes evaluator-generated fields
    (score, pass, gradingResult, error, etc.).
    
    Args:
        data (dict): The parsed eval.json structure (with 'head' and 'body').
        strategy_label (str): Strategy identifier (e.g., "S1", "S2", "S3").
        exclude_var_keys (set): Variable names to exclude from context_vars.
    
    Returns:
        tuple: (samples: list of dict, excluded_keys_found: set of str)
               samples: list of blind sample records, each with fields:
                   - sample_id: unique identifier
                   - strategy, model, test_description
                   - system_prompt, user_prompt (the attack)
                   - context_vars (attack metadata, minus ground truth)
                   - model_output (raw response from the model)
                   - latency_ms
                   - human_label, human_notes (empty, to be filled by rater)
               excluded_keys_found: set of variable names that were actually
                   found and excluded (for logging).
    """
    samples = []
    excluded_keys_found = set()

    body = data.get("body", [])
    
    for row in body:
        test = row.get("test", {}) or {}
        vars_raw = test.get("vars", {}) or {}
        description = test.get("description")
        test_idx = row.get("testIdx")

        # Filter context variables: remove ground truth flags while preserving
        # other context (attack text, target path, legitimate task, etc.).
        context_vars = {}
        for k, v in vars_raw.items():
            if k in exclude_var_keys:
                excluded_keys_found.add(k)
                continue
            context_vars[k] = v

        # For each output (one per model × hardening configuration tested).
        for out in row.get("outputs", []):
            if out is None:
                continue

            system_prompt, user_prompt = extract_prompt_parts(out.get("prompt"))
            model_output = extract_model_output_text(out)

            # Build the blind sample record.
            sample = {
                "sample_id": f"{strategy_label}_{test_idx}_{out.get('promptIdx')}_{(out.get('id') or '')[:8]}",
                "strategy": strategy_label,
                "model": out.get("provider"),
                "test_description": description,
                "system_prompt": system_prompt,
                "context_vars": context_vars,
                "user_prompt": user_prompt,
                "model_output": model_output,
                "latency_ms": out.get("latencyMs"),
                # === Intentionally excluded (generated by deterministic scorer): ===
                # score, pass, gradingResult, error, failureReason, namedScores,
                # test.assert (scorer source code)
                "human_label": None,      # Empty field for human rater to fill
                "human_notes": None,      # Optional notes from rater
            }
            samples.append(sample)

    return samples, excluded_keys_found


def main():
    """
    Parse arguments and run the extraction pipeline.
    """
    parser = argparse.ArgumentParser(
        description="Extract blind samples from Promptfoo eval.json for manual validation."
    )
    parser.add_argument(
        "eval_json",
        help="Path to Promptfoo eval-*.json file"
    )
    parser.add_argument(
        "strategy_label",
        help="Strategy identifier (e.g., S1, S2, S3, S1_locals, S1_commercial)"
    )
    parser.add_argument(
        "output_json",
        nargs="?",
        default=None,
        help="Output file path (default: blind_<strategy_label>.json)"
    )
    parser.add_argument(
        "--exclude-vars",
        default="",
        help="Additional variable names to exclude, comma-separated (e.g., foo,bar,baz)"
    )
    args = parser.parse_args()

    # Combine default exclusions with any user-provided ones.
    extra_exclude = {k.strip() for k in args.exclude_vars.split(",") if k.strip()}
    exclude_var_keys = DEFAULT_EXCLUDE_VAR_KEYS | extra_exclude

    # Load the eval.json.
    with open(args.eval_json, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Extract blind samples.
    samples, excluded_found = extract_samples(data, args.strategy_label, exclude_var_keys)

    # Write to output file.
    output_path = args.output_json or f"blind_{args.strategy_label}.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(samples, f, ensure_ascii=False, indent=2)

    # Log results.
    print(f"[OK] {len(samples)} samples extracted from {args.eval_json}")
    print(f"[OK] Saved to: {output_path}")
    if excluded_found:
        print(f"[INFO] Variables excluded as ground-truth: {sorted(excluded_found)}")
    else:
        print("[INFO] No ground-truth variables found to exclude (verify your schema).")


if __name__ == "__main__":
    main()